config/routes.rb
Rails.application.routes.draw do
resources :posts
resources :authors

  get '/' => 'posts#index'
  

  post '/login', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

end

app/models/author.rb
class Author < ActiveRecord::Base

  has_many :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :postname, presence: true, uniqueness: true
  validates :email, presence: true

  belongs_to :author

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :password, confirmation: true
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to posts_path, alert: 'You must be logged in to view this page' if current_user.nil?
  end

  helper_method :current_user
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authorize, except: [:index, :show]

  
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find_by_id(params[:id])
    @posts = @author.posts
  end

  def new
    @author = Author.new
  end

  def edit
    @author = Author.find_by_id(params[:id])
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to author_path(@author), notice: "Author was created successfully"
    else
      flash[:alert] = "There was an error creating an author"
      render :new
    end
  end

  def update
    @author = Author.find_by_id(params[:id])
    if @author.update_attributes(author_params)
      redirect_to authors_path, notice: "Author was updated successfully"
    else
      flash[:alert] = "Error!"
      render :edit
    end
  end

  def destroy
    @author = Author.find_by_id(params[:id])

    if @author.destroy
      flash[:notice] = "#{@author.fname} was sucessfully deleted."
    else
      flash[:alert] = "There was an error while attempting to delete this author."
    end

    redirect_to authors_path
  end

  private

  def author_params
    params.require(:author).permit(:fname, :lname, :post_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by_id(params[:id])
    @author = @post.author
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find_by_id(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_path(@post), notice: "Post was uploaded successfully"
    else
      flash[:alert] = "There was an error posting a post"
      render :new
    end
  end

  def update
    @post = Post.find_by_id(params[:id])
    if @post.update_attributes(post_params)
      redirect_to posts_path, notice: "Post was updated sucessfully"
    else
      flash[:alert] = "Error!"
      render :edit
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])

    if @post.destroy
      flash[:notice] = "#{@post.postname} was sucessfully deleted."
    else
      flash[:alert] = "There was an error while attempting to delete this post."
    end

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:email, :postname, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authorize, only: [:destroy]

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path, notice: "Welcome back, #{user.email}!"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to posts_path, notice: "Successfully logged out"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
  <%= f.label :fname, "First Name" %>
  <%= f.text_field :fname %> <br>

  <%= f.label :lname, "Last Name" %>
  <%= f.text_field :lname %> <br>

  <%= f.collection_select(:post_id, Post.all, :id, :postname, prompt: true) %>

  <%= f.submit %>


<% end %>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= render "form" %>

app/views/authors/index.html.erb
<h1>List of Authors</h1>

<div class="newpost">
  <%= link_to "Add new Author", new_author_path %>
</div>


  <% @authors.each do |author| %>

    <div class="postname">
        <%= link_to author.fname, author_path(author) %>
    </div>

    <div class="time">
      <%= author.created_at %>
    </div>

  <div class="delete">
    <%= link_to "Delete", author_path(author), method: :delete, data: {confirm: "Are you sure?"} %>
  </div>


  <% end %>
</ul>

app/views/authors/new.html.erb
<h1>Add New Author</h1>

<%= render "form" %>

app/views/authors/show.html.erb
<h1>Author Details</h1>

<%= link_to "Back to Author List", authors_path %>
<%= link_to "Edit", edit_author_path(@author) %>

<h2><span>Author First Name</span>: <%= @author.fname %></h2>
<h2><span>Author Last Name</span>: <%= @author.lname %></h2>
<h2><span>Author Created at</span>: <%= @author.created_at %></h2>

<h2> Posts </h2>
  <ul>
    <% @posts.each do |post| %>
      <li><%= link_to post.postname, post_path(post) %></li>
    <% end %>
  </ul>

app/views/home/index.html.erb
<h1>Blog Home</h1>
<!-- Re-directing to Posts Index page -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= flash[:notice] if flash[:notice] %>
  <%= flash[:alert] if flash[:alert] %>

  <% if current_user %>
    <%= current_user.email %>
    <%= link_to "Logout", logout_path, method: :delete %>
  <% else %>
    <%= link_to "Login", login_path %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

<div class="newpostname">
  <%= f.label :postname %>
  <%= f.text_field :postname %>
</div>

  </br>

<div class="newpostname">
  <%= f.label :content %>
  <%= f.text_field :content %>
</div>

  </br>

<div class="newpostname">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>

  </br>

<h4>Author</h4>
<div class="newpostname">
  <%= f.collection_select(:author_id, Author.all, :id, :fname, prompt: true) %>
</div>

  </br>

<div class="submit">
  <%= f.submit %>
</div>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>This Week's List of Blog Posts</h1>

<div class="newpost">
  <%= link_to "Add new Post", new_post_path %>
</div>


  <% @posts.each do |post| %>

    <div class="postname">
        <%= link_to post.postname, post_path(post) %>
    </div>

    <div class="time">
      <%= post.created_at %>
    </div>

  <div class="delete">
    <%= link_to "Delete", post_path(post), method: :delete, data: {confirm: "Are you sure?"} %>
  </div>


  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>Add a New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1>Detailed Blog Post</h1>

<div class="back">
  <%= link_to "Back to This Week's List of Blog Posts", posts_path %>
</div>

<div class="back">
  <%= link_to "Edit", edit_post_path(@post) %>
</div>

<div class="postname2">
  <%= @post.postname %>
</div>

<div class="name">
  <%= @post.content %>
</div>
  
<div class="email">
  <%= @post.email %>
</div>

<div class="email">
    Author Name : <%= @author.fname %> <%= @author.lname %>
</div>


<div class="time2">
  <%= @post.created_at %>
</div>